import type {
  User,
  DoctorProfile,
  PharmacyProfile,
  PatientProfile,
  Medicine,
  Appointment,
  Order,
  ChatMessage,
  ChatRoom,
  Transaction,
  Notification,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Ahmad Hidayat',
    email: 'ahmad@gmail.com',
    role: 'patient',
    avatar: '/avatars/patient-1.jpg',
    phone: '+62812345678',
    createdAt: '2024-01-15',
  },
  {
    id: 'user-2',
    name: 'Dr. Sarah Wijaya',
    email: 'sarah@gmail.com',
    role: 'doctor',
    avatar: '/avatars/doctor-1.jpg',
    phone: '+62823456789',
    createdAt: '2024-01-10',
  },
  {
    id: 'user-3',
    name: 'Dr. Budi Santoso',
    email: 'budi@gmail.com',
    role: 'doctor',
    avatar: '/avatars/doctor-2.jpg',
    phone: '+62834567890',
    createdAt: '2024-01-08',
  },
  {
    id: 'user-4',
    name: 'Apotek Sehat Selalu',
    email: 'sehat@gmail.com',
    role: 'pharmacy',
    avatar: '/avatars/pharmacy-1.jpg',
    phone: '+62845678901',
    createdAt: '2024-01-05',
  },
  {
    id: 'user-5',
    name: 'Admin HealthServices',
    email: 'admin@gmail.com',
    role: 'admin',
    avatar: '/avatars/admin-1.jpg',
    phone: '+62856789012',
    createdAt: '2024-01-01',
  },
  {
    id: 'user-6',
    name: 'Dr. Maya Putri',
    email: 'maya@gmail.com',
    role: 'doctor',
    avatar: '/avatars/doctor-3.jpg',
    phone: '+62867890123',
    createdAt: '2024-01-12',
  },
  {
    id: 'user-7',
    name: 'Dr. Rizki Pratama',
    email: 'rizki@gmail.com',
    role: 'doctor',
    avatar: '/avatars/doctor-4.jpg',
    phone: '+62878901234',
    createdAt: '2024-01-14',
  },
  {
    id: 'user-8',
    name: 'Siti Rahayu',
    email: 'siti@gmail.com',
    role: 'patient',
    avatar: '/avatars/patient-2.jpg',
    phone: '+62889012345',
    createdAt: '2024-01-20',
  },
]

// Mock Doctor Profiles
export const mockDoctors: DoctorProfile[] = [
  {
    id: 'doc-1',
    userId: 'user-2',
    user: mockUsers[1],
    specialization: 'Dokter Umum',
    hospital: 'RS Cipto Mangunkusumo',
    experience: 8,
    rating: 4.9,
    reviewCount: 1250,
    price: 75000,
    bio: 'Dokter umum berpengalaman dengan fokus pada kesehatan keluarga dan pencegahan penyakit.',
    education: ['Universitas Indonesia - Kedokteran', 'Spesialis Kedokteran Keluarga'],
    availableSlots: [
      { id: 'slot-1', date: '2024-12-20', startTime: '09:00', endTime: '09:30', isBooked: false },
      { id: 'slot-2', date: '2024-12-20', startTime: '09:30', endTime: '10:00', isBooked: true },
      { id: 'slot-3', date: '2024-12-20', startTime: '10:00', endTime: '10:30', isBooked: false },
    ],
    isVerified: true,
    isOnline: true,
    practiceAddress: 'Klinik Keluarga Sehat, Jl. Sudirman No. 12, Jakarta',
  },
  {
    id: 'doc-2',
    userId: 'user-3',
    user: mockUsers[2],
    specialization: 'Spesialis Jantung',
    hospital: 'RS Harapan Kita',
    experience: 15,
    rating: 4.8,
    reviewCount: 890,
    price: 250000,
    bio: 'Spesialis jantung dengan pengalaman lebih dari 15 tahun dalam penanganan penyakit kardiovaskular.',
    education: ['Universitas Gadjah Mada - Kedokteran', 'Spesialis Jantung dan Pembuluh Darah - UI'],
    availableSlots: [
      { id: 'slot-4', date: '2024-12-21', startTime: '14:00', endTime: '14:30', isBooked: false },
      { id: 'slot-5', date: '2024-12-21', startTime: '14:30', endTime: '15:00', isBooked: false },
    ],
    isVerified: true,
    isOnline: true,
    practiceAddress: 'Praktek Jantung Harapan, Jl. Gatot Subroto No. 45, Jakarta',
  },
  {
    id: 'doc-3',
    userId: 'user-6',
    user: mockUsers[5],
    specialization: 'Spesialis Kulit',
    hospital: 'RS Pondok Indah',
    experience: 10,
    rating: 4.7,
    reviewCount: 650,
    price: 200000,
    bio: 'Dermatolog dengan keahlian dalam perawatan kulit, estetika, dan penanganan penyakit kulit kronis.',
    education: ['Universitas Airlangga - Kedokteran', 'Spesialis Kulit dan Kelamin - FKUI'],
    availableSlots: [
      { id: 'slot-6', date: '2024-12-20', startTime: '11:00', endTime: '11:30', isBooked: false },
    ],
    isVerified: true,
    isOnline: true,
    practiceAddress: 'Klinik Kulit Cantik, Jl. Pondok Indah No. 8, Jakarta',
  },
  {
    id: 'doc-4',
    userId: 'user-7',
    user: mockUsers[6],
    specialization: 'Spesialis Anak',
    hospital: 'RS Bunda',
    experience: 12,
    rating: 4.9,
    reviewCount: 1100,
    price: 180000,
    bio: 'Dokter spesialis anak yang berdedikasi untuk kesehatan dan tumbuh kembang anak.',
    education: ['Universitas Padjadjaran - Kedokteran', 'Spesialis Anak - FKUI'],
    availableSlots: [
      { id: 'slot-7', date: '2024-12-22', startTime: '08:00', endTime: '08:30', isBooked: false },
      { id: 'slot-8', date: '2024-12-22', startTime: '08:30', endTime: '09:00', isBooked: false },
    ],
    isVerified: true,
    isOnline: true,
    practiceAddress: 'Klinik Anak Ceria, Jl. Kemang Raya No. 15, Jakarta',
  },
]

// Mock Patient Profiles
export const mockPatients: PatientProfile[] = [
  {
    id: 'pat-1',
    userId: 'user-1',
    user: mockUsers[0],
    dateOfBirth: '1990-05-15',
    gender: 'male',
    bloodType: 'O+',
    allergies: ['Penisilin'],
    medicalHistory: ['Asma ringan'],
    address: 'Jl. Sudirman No. 123, Jakarta Selatan',
  },
  {
    id: 'pat-2',
    userId: 'user-8',
    user: mockUsers[7],
    dateOfBirth: '1985-08-22',
    gender: 'female',
    bloodType: 'A+',
    allergies: [],
    medicalHistory: ['Hipertensi terkontrol'],
    address: 'Jl. Gatot Subroto No. 456, Jakarta Pusat',
  },
]

// Mock Pharmacy Profiles
export const mockPharmacies: PharmacyProfile[] = [
  {
    id: 'pharm-1',
    userId: 'user-4',
    user: mockUsers[3],
    name: 'Apotek Sehat Selalu',
    address: 'Jl. Thamrin No. 100, Jakarta Pusat',
    city: 'Jakarta',
    phone: '+62845678901',
    operatingHours: '08:00 - 22:00',
    isVerified: true,
    isOpen: true,
    rating: 4.6,
    reviewCount: 320,
  },
]

// Mock Medicines
export const mockMedicines: Medicine[] = [
  {
    id: 'med-1',
    name: 'Paracetamol 500mg',
    genericName: 'Paracetamol',
    description: 'Obat pereda nyeri dan penurun demam',
    category: 'Analgesik',
    price: 15000,
    stock: 100,
    unit: 'Strip (10 tablet)',
    requiresPrescription: false,
    image: '/medicines/paracetamol.jpg',
    pharmacyId: 'pharm-1',
  },
  {
    id: 'med-2',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin',
    description: 'Antibiotik untuk infeksi bakteri',
    category: 'Antibiotik',
    price: 35000,
    stock: 50,
    unit: 'Strip (10 kapsul)',
    requiresPrescription: true,
    image: '/medicines/amoxicillin.jpg',
    pharmacyId: 'pharm-1',
  },
  {
    id: 'med-3',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole',
    description: 'Obat untuk mengurangi asam lambung',
    category: 'Gastrointestinal',
    price: 45000,
    stock: 75,
    unit: 'Strip (10 kapsul)',
    requiresPrescription: false,
    image: '/medicines/omeprazole.jpg',
    pharmacyId: 'pharm-1',
  },
  {
    id: 'med-4',
    name: 'Cetirizine 10mg',
    genericName: 'Cetirizine',
    description: 'Obat anti alergi',
    category: 'Antihistamin',
    price: 25000,
    stock: 80,
    unit: 'Strip (10 tablet)',
    requiresPrescription: false,
    image: '/medicines/cetirizine.jpg',
    pharmacyId: 'pharm-1',
  },
  {
    id: 'med-5',
    name: 'Vitamin C 1000mg',
    genericName: 'Ascorbic Acid',
    description: 'Suplemen untuk meningkatkan daya tahan tubuh',
    category: 'Vitamin',
    price: 55000,
    stock: 120,
    unit: 'Botol (30 tablet)',
    requiresPrescription: false,
    image: '/medicines/vitamin-c.jpg',
    pharmacyId: 'pharm-1',
  },
  {
    id: 'med-6',
    name: 'Ibuprofen 400mg',
    genericName: 'Ibuprofen',
    description: 'Obat anti inflamasi non-steroid',
    category: 'Analgesik',
    price: 20000,
    stock: 90,
    unit: 'Strip (10 tablet)',
    requiresPrescription: false,
    image: '/medicines/ibuprofen.jpg',
    pharmacyId: 'pharm-1',
  },
]

// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    id: 'apt-1',
    patientId: 'pat-1',
    patient: mockPatients[0],
    doctorId: 'doc-1',
    doctor: mockDoctors[0],
    date: '2024-12-20',
    time: '09:00',
    type: 'online',
    status: 'confirmed',
    complaint: 'Demam dan batuk selama 3 hari',
    createdAt: '2024-12-18',
  },
  {
    id: 'apt-2',
    patientId: 'pat-1',
    patient: mockPatients[0],
    doctorId: 'doc-2',
    doctor: mockDoctors[1],
    date: '2024-12-15',
    time: '14:00',
    type: 'offline',
    status: 'completed',
    complaint: 'Kontrol rutin jantung',
    diagnosis: 'Kondisi jantung stabil, lanjutkan pengobatan',
    notes: 'Pasien dalam kondisi baik, disarankan olahraga ringan',
    practiceAddress: 'Praktek Jantung Harapan, Jl. Gatot Subroto No. 45, Jakarta',
    createdAt: '2024-12-10',
  },
  {
    id: 'apt-3',
    patientId: 'pat-2',
    patient: mockPatients[1],
    doctorId: 'doc-3',
    doctor: mockDoctors[2],
    date: '2024-12-22',
    time: '11:00',
    type: 'online',
    status: 'pending',
    complaint: 'Ruam kulit di area lengan',
    createdAt: '2024-12-19',
  },
]

// Mock Orders
export const mockOrders: Order[] = [
  {
    id: 'ord-1',
    patientId: 'pat-1',
    patient: mockPatients[0],
    pharmacyId: 'pharm-1',
    pharmacy: mockPharmacies[0],
    items: [
      { medicineId: 'med-1', medicine: mockMedicines[0], quantity: 2, price: 30000 },
      { medicineId: 'med-5', medicine: mockMedicines[4], quantity: 1, price: 55000 },
    ],
    totalAmount: 85000,
    status: 'delivered',
    shippingAddress: 'Jl. Sudirman No. 123, Jakarta Selatan',
    paymentStatus: 'paid',
    createdAt: '2024-12-15',
  },
  {
    id: 'ord-2',
    patientId: 'pat-1',
    patient: mockPatients[0],
    pharmacyId: 'pharm-1',
    pharmacy: mockPharmacies[0],
    items: [
      { medicineId: 'med-3', medicine: mockMedicines[2], quantity: 1, price: 45000 },
    ],
    totalAmount: 45000,
    status: 'processing',
    shippingAddress: 'Jl. Sudirman No. 123, Jakarta Selatan',
    paymentStatus: 'paid',
    createdAt: '2024-12-19',
  },
]

// Mock Chat Messages
export const mockChatMessages: ChatMessage[] = [
  {
    id: 'msg-1',
    senderId: 'user-1',
    receiverId: 'user-2',
    content: 'Selamat pagi Dok, saya ingin konsultasi tentang demam yang saya alami',
    type: 'text',
    createdAt: '2024-12-20T08:30:00',
    isRead: true,
  },
  {
    id: 'msg-2',
    senderId: 'user-2',
    receiverId: 'user-1',
    content: 'Selamat pagi. Sudah berapa hari demamnya? Apakah ada gejala lain?',
    type: 'text',
    createdAt: '2024-12-20T08:32:00',
    isRead: true,
  },
  {
    id: 'msg-3',
    senderId: 'user-1',
    receiverId: 'user-2',
    content: 'Sudah 3 hari Dok. Ada batuk dan pilek juga.',
    type: 'text',
    createdAt: '2024-12-20T08:35:00',
    isRead: false,
  },
]

// Mock Chat Rooms
export const mockChatRooms: ChatRoom[] = [
  {
    id: 'room-1',
    appointmentId: 'apt-1',
    participants: [mockUsers[0], mockUsers[1]],
    lastMessage: mockChatMessages[2],
    unreadCount: 1,
    createdAt: '2024-12-20T08:30:00',
  },
]

// Mock Transactions
export const mockTransactions: Transaction[] = [
  {
    id: 'trx-1',
    userId: 'user-1',
    type: 'appointment',
    referenceId: 'apt-1',
    amount: 75000,
    status: 'paid',
    paymentMethod: 'Bank Transfer',
    createdAt: '2024-12-18',
  },
  {
    id: 'trx-2',
    userId: 'user-1',
    type: 'order',
    referenceId: 'ord-1',
    amount: 85000,
    status: 'paid',
    paymentMethod: 'E-Wallet',
    createdAt: '2024-12-15',
  },
  {
    id: 'trx-3',
    userId: 'user-1',
    type: 'order',
    referenceId: 'ord-2',
    amount: 45000,
    status: 'paid',
    paymentMethod: 'Credit Card',
    createdAt: '2024-12-19',
  },
]

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-1',
    title: 'Konsultasi Dikonfirmasi',
    message: 'Konsultasi dengan Dr. Sarah Wijaya pada 20 Des 2024 pukul 09:00 telah dikonfirmasi',
    type: 'appointment',
    isRead: false,
    createdAt: '2024-12-19T10:00:00',
  },
  {
    id: 'notif-2',
    userId: 'user-1',
    title: 'Pesanan Dikirim',
    message: 'Pesanan obat Anda sedang dalam perjalanan',
    type: 'order',
    isRead: true,
    createdAt: '2024-12-19T14:00:00',
  },
]

// Specializations list
export const specializations = [
  'Dokter Umum',
  'Spesialis Jantung',
  'Spesialis Kulit',
  'Spesialis Anak',
  'Spesialis Mata',
  'Spesialis THT',
  'Spesialis Saraf',
  'Spesialis Paru',
  'Spesialis Bedah',
  'Psikiater',
  'Dokter Gigi',
]

// Medicine categories
export const medicineCategories = [
  'Analgesik',
  'Antibiotik',
  'Antihistamin',
  'Gastrointestinal',
  'Vitamin',
  'Obat Batuk & Pilek',
  'Obat Kulit',
  'Obat Mata',
  'Suplemen',
]
